"""airtime merchant vertical — merchant_profiles + airtime_recharges (Epic 17)

Revision ID: 0024
Revises: 0023
Create Date: 2026-07-09 11:26:19.428539

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0024"
down_revision: str | Sequence[str] | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("service_code", sa.String(length=50), nullable=False),
        sa.Column("mode", sa.String(length=20), server_default="simulator", nullable=False),
        sa.Column(
            "provider_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("callback_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('simulator', 'live')", name="ck_merchant_profiles_mode"),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_merchant_profiles_status"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_merchant_profiles_tenant", "merchant_profiles", ["tenant_id"], unique=False)
    op.create_index(
        "ix_merchant_profiles_tenant_service",
        "merchant_profiles",
        ["tenant_id", "service_code", "status"],
        unique=False,
    )
    op.create_index(
        "uq_merchant_profiles_active_service",
        "merchant_profiles",
        ["tenant_id", "service_code"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index("uq_merchant_profiles_user", "merchant_profiles", ["user_id"], unique=True)
    op.create_table(
        "airtime_recharges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("msisdn", sa.String(length=20), nullable=False),
        sa.Column("network", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED')",
            name="ck_airtime_recharges_status",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_airtime_recharges_idempotency_per_tenant"
        ),
    )
    op.create_index(
        "ix_airtime_recharges_status",
        "airtime_recharges",
        ["status", "tenant_id"],
        unique=False,
    )
    op.create_index("ix_airtime_recharges_tenant", "airtime_recharges", ["tenant_id"], unique=False)
    op.create_index("ix_airtime_recharges_user", "airtime_recharges", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_airtime_recharges_user", table_name="airtime_recharges")
    op.drop_index("ix_airtime_recharges_tenant", table_name="airtime_recharges")
    op.drop_index("ix_airtime_recharges_status", table_name="airtime_recharges")
    op.drop_table("airtime_recharges")
    op.drop_index("uq_merchant_profiles_user", table_name="merchant_profiles")
    op.drop_index(
        "uq_merchant_profiles_active_service",
        table_name="merchant_profiles",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_merchant_profiles_tenant_service", table_name="merchant_profiles")
    op.drop_index("ix_merchant_profiles_tenant", table_name="merchant_profiles")
    op.drop_table("merchant_profiles")
    # ### end Alembic commands ###
